#!/usr/bin/env bash
# Creates the fixed signing keystore used for every ClassTime build, and writes
# the untracked keystore.properties that points at it.
#
# This key is what lets a new build install *over* the installed app. Keep it:
# if you lose it, the only way to install a future build on a phone that already
# has ClassTime is to uninstall the app first (which wipes its data).
#
#   ./scripts/create-keystore.sh [--password <pw>] [--path <file>] [--alias <a>]
set -euo pipefail

source "$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)/env.sh"

KS_PATH=""
KS_PASS=""
KS_ALIAS=""
KS_DNAME="${CLASSTIME_KEY_DNAME:-CN=ClassTime, OU=Development, O=ClassTime, C=KR}"

while [ $# -gt 0 ]; do
  case "$1" in
    --password) KS_PASS="${2:-}"; shift 2 ;;
    --path)     KS_PATH="${2:-}"; shift 2 ;;
    --alias)    KS_ALIAS="${2:-}"; shift 2 ;;
    -h|--help)  awk 'NR>1 && /^#/ { sub(/^# ?/, ""); print; next } NR>1 { exit }' "$0"; exit 0 ;;
    *) die "Unknown option: $1" ;;
  esac
done

PROPS_FILE="$REPO_ROOT/keystore.properties"

prop() { # prop <key>; reads keystore.properties
  [ -f "$PROPS_FILE" ] || return 0
  local v
  v="$(sed -nE "s/^[[:space:]]*$1=(.*)\$/\1/p" "$PROPS_FILE" 2>/dev/null || true)"
  printf '%s' "${v%%$'\n'*}"
}

# Existing config wins so re-running is harmless.
KS_PATH="${KS_PATH:-${CLASSTIME_KEYSTORE_FILE:-$(prop storeFile)}}"
KS_PATH="${KS_PATH:-secrets/classtime-release.jks}"
KS_ALIAS="${KS_ALIAS:-${CLASSTIME_KEY_ALIAS:-$(prop keyAlias)}}"
KS_ALIAS="${KS_ALIAS:-classtime}"
KS_PASS="${KS_PASS:-${CLASSTIME_KEYSTORE_PASSWORD:-$(prop storePassword)}}"
[ "$KS_PASS" = "CHANGE_ME" ] && KS_PASS=""

# Resolve the keystore path the same way the Gradle build does.
case "$KS_PATH" in
  "~/"*) ABS_PATH="$HOME/${KS_PATH#\~/}" ;;
  /*)    ABS_PATH="$KS_PATH" ;;
  *)     ABS_PATH="$REPO_ROOT/$KS_PATH" ;;
esac

if [ -f "$ABS_PATH" ]; then
  ok "Keystore already exists at $ABS_PATH - leaving it untouched."
  warn "Never regenerate this file: a different key breaks in-place updates."
  if [ -f "$PROPS_FILE" ] && [ -n "$(prop storePassword)" ] && [ "$(prop storePassword)" != "CHANGE_ME" ]; then
    ok "keystore.properties already configured."
  else
    warn "But keystore.properties has no usable password. Fill it in by hand:"
    warn "  storeFile=$KS_PATH"
    warn "  storePassword=<the password you used>"
    warn "  keyAlias=$KS_ALIAS"
  fi
  exit 0
fi

# keytool comes from the JDK; any JDK will do for this.
if JDK_PATH="$(find_supported_jdk)"; then
  KEYTOOL="$JDK_PATH/bin/keytool"
elif [ -n "${JAVA_HOME:-}" ] && [ -x "$JAVA_HOME/bin/keytool" ]; then
  KEYTOOL="$JAVA_HOME/bin/keytool"
elif command -v keytool >/dev/null 2>&1; then
  KEYTOOL="$(command -v keytool)"
else
  die "keytool not found. Run ./scripts/setup-build-env.sh first."
fi

if [ -z "$KS_PASS" ]; then
  # Bounded input so nothing in the pipeline closes early and raises SIGPIPE
  # (which `set -o pipefail` would turn into a hard failure).
  KS_PASS="$(head -c 512 /dev/urandom | LC_ALL=C tr -dc 'A-Za-z0-9' | cut -c1-32)"
  GENERATED_PASS=1
else
  GENERATED_PASS=0
fi
[ "${#KS_PASS}" -ge 6 ] || die "Keystore password must be at least 6 characters."

mkdir -p "$(dirname "$ABS_PATH")"

log "Creating keystore at $ABS_PATH (alias: $KS_ALIAS) ..."
"$KEYTOOL" -genkeypair \
  -keystore "$ABS_PATH" \
  -storetype PKCS12 \
  -alias "$KS_ALIAS" \
  -keyalg RSA -keysize 4096 \
  -validity 10000 \
  -dname "$KS_DNAME" \
  -storepass "$KS_PASS" \
  -keypass "$KS_PASS" >/dev/null
chmod 600 "$ABS_PATH"
ok "Keystore created."

# PKCS12 keeps the key password identical to the store password, so only
# storePassword is written here; the build reuses it for keyPassword.
if [ ! -f "$PROPS_FILE" ] || [ -z "$(prop storePassword)" ] || [ "$(prop storePassword)" = "CHANGE_ME" ]; then
  cat > "$PROPS_FILE" <<PROPS
# Generated by scripts/create-keystore.sh. Gitignored - never commit this file.
# Environment variables of the same meaning take precedence:
#   CLASSTIME_KEYSTORE_FILE / CLASSTIME_KEYSTORE_PASSWORD / CLASSTIME_KEY_ALIAS
storeFile=$KS_PATH
storePassword=$KS_PASS
keyAlias=$KS_ALIAS
PROPS
  chmod 600 "$PROPS_FILE"
  ok "Wrote keystore.properties (mode 600, gitignored)."
fi

echo
if [ "$GENERATED_PASS" -eq 1 ]; then
  log "A random password was generated and stored in keystore.properties:"
  echo "    $KS_PASS"
  warn "Back up BOTH $ABS_PATH and this password somewhere safe (password manager)."
else
  warn "Back up $ABS_PATH and its password somewhere safe."
fi
echo
log "Certificate fingerprint (what Android checks on update):"
"$KEYTOOL" -list -v -keystore "$ABS_PATH" -alias "$KS_ALIAS" -storepass "$KS_PASS" 2>/dev/null \
  | sed -nE 's/^[[:space:]]*(SHA1|SHA256):[[:space:]]*(.*)$/    \1: \2/p'
